## Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"

## Terminal
brew "zsh"
brew "bash-completion"

## General
cask "raycast"

## Developer tools
brew "git"
brew "awscli"
brew "git-remote-codecommit"
brew "bitwarden-cli"
cask "aws-vault"
cask "session-manager-plugin"

## Entertainment
cask "zwift"
