## Taps
tap "homebrew/bundle"

## Terminal
brew "zsh"
brew "bash-completion"

## General
cask "raycast"

## Developer tools
brew "git"
brew "asdf"
brew "awscli"
brew "git-remote-codecommit"
brew "bitwarden-cli"
cask "aws-vault"
cask "session-manager-plugin"
