## Terminal
brew "zsh"
brew "bash-completion"

## General
cask "raycast"
cask "chatgpt"

## Developer tools
brew "git"
brew "gpg"
brew "pinentry-mac"
brew "asdf"
brew "git-remote-codecommit"
brew "bitwarden-cli"
brew "tmux"
brew "structurizr-cli"
cask "aws-vault-binary"
cask "session-manager-plugin"
cask "docker-desktop"
cask "windows-app"
cask "virtualbox"
cask "google-chrome"
cask "imageoptim"
cask "intellij-idea"
cask "miro"

